runtime: nodejs10
handlers:
  #serve all static file with urls ending with a file extension
- url: /(.*\..+)$
  static_files: build/\1
  upload: build/(.*\..+)$
  # catch all handler to index.html
- url: /.*
  static_files: build/index.html
  upload: build/index.html